def execute(block)
  block.call
end

execute { puts "Hello from inside the method!" }

raises error:

block.rb1:in 'execute': wrong number of arguments (0 for 1) (ArgumentError)
from test.rb:5:in '<main>'

The method argument "block" should have an "&" appended to it,
this will allow a block to be passed to the method.
